environment:
  matrix:
  - nodejs_version: 0.12
  - nodejs_version: 4
  - nodejs_version: 6

  GCLOUD_TESTS_KEY: key.appveyor.json
  GCLOUD_TESTS_KEY_SECRET:
    secure: usGkvXjqCzDNIQHx8oEncrZOmez7GBocB1EXM+g/9rw=

cache:
  - node_modules
  - packages\bigquery\node_modules
  - packages\bigtable\node_modules
  - packages\compute\node_modules
  - packages\datastore\node_modules
  - packages\dns\node_modules
  - packages\google-cloud\node_modules
  - packages\language\node_modules
  - packages\logging\node_modules
  - packages\prediction\node_modules
  - packages\pubsub\node_modules
  - packages\resource\node_modules
  - packages\storage\node_modules
  - packages\translate\node_modules
  - packages\vision\node_modules
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: >-
      if (!$env:APPVEYOR_PULL_REQUEST_NUMBER) {
        nuget install secure-file -ExcludeVersion
        secure-file\tools\secure-file -decrypt key.appveyor.json.enc -secret $env:GCLOUD_TESTS_KEY_SECRET
      }
  - npm install -g npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - ps: if (!$env:APPVEYOR_PULL_REQUEST_NUMBER) { npm run system-test }

build: off

matrix:
  fast_finish: true