language: node_js
node_js:
  - 0.12
  - 4
  - 6
os:
  - linux
  - osx
before_install:
  - npm install -g npm # Force using the latest npm to get dedupe during install
script: "./scripts/build.sh"
before_deploy: "./scripts/release.sh"
sudo: false
